version: '3.11-slim-buster'


services:
  postgres:
    image: postgres:13
    container_name: some-postgres
    environment:
      POSTGRES_DB: fl_django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nana 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - novem/.env #switch to /.env_example  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - novem/.env #switch to /.env_example 

volumes:
  pgdata:
